[workspace]
channels = ["conda-forge"]
name = "EpicsServer"
platforms = ["win-64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "<3.13"
numpy = "*"
matplotlib = "*"
ipython = "*"

[pypi-dependencies]
caproto = { version = ">=0.4.2rc1,!=1.2.0", extras = ["standard"] }
ophyd = "*"

[environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[feature.dev.dependencies]
pre-commit = "*"
ruff = "*"
pyright = "*"
